### ISSUE TITLE
Mise en place appli de génération de token OAuth2

### ISSUE THREAD

**Issue by rjansem** [SopraSteriaGroup/initiatives_backend#14]
Mise en oeuvre d'une application fédérant les authentifications. Dans un premier temps récupérer un token depuis LinkedIn et générer notre token OAuth2 depuis l'application auth-service

**Comment by cegiraud** [comment]
Fait. 
Il reste un TODO pour penser à appeler le MS sopridee pour récupérer les rôles de l'utilisateur.

**Comment by jntakpe** [comment]
@cegiraud nice :)

**Comment by cegiraud** [comment]
Je close. Le reste sera géré dans #7
