### ISSUE TITLE
Connection avec linkedin

### ISSUE THREAD

**Issue by cegiraud** [SopraSteriaGroup/initiatives_backend#16]
Checker ce qui est possible comme flow avec linkedin.
Utilisation de SpringBoot social linkedin.

**Comment by cegiraud** [comment]
Sera effectué côté client.
Le client transmettra uniquement l'access token au back

**Comment by jntakpe** [comment]
@cegiraud Par contre la question est de savoir si on ne veut pas quand même récupérer des informations contenues dans le token pour mapper l'adresse Sopra sur le compte LinkedIn

**Comment by cegiraud** [comment]
Sur le token on va avoir du mal a priori. Par contre je pense qu'il faut faire un appel à la page de profil ce qui permettra : 
1 de valider le token
2 de réccupérer des infos du profil
