### ISSUE TITLE
Procédure d'activation d'un compte

### ISSUE THREAD

**Issue by rjansem** [SopraSteriaGroup/initiatives_backend#19]
Comme vu avec @cegiraud (procédure à valider avec le mobile) :

- L'auth-service est serveur d'autorisation, le token linkedin n'étant utilisé que pour s'assurer que l'utilisateur est bien authentifié et accéder à son ID via les API linkedin.
- A la saisie de l'adresse email, un endpoint est appelé côté user-service pour générer un code et l'envoyer par email (cf #8 )
- Côté mobile, l'IHM affiche ensuite un écran permettant de saisir ce code.
- Si l'utilisateur ne saisit pas le code immédiatement, à la prochaine connexion, le rôle utilisateur retourné par le auth-service permettra au mobile de détecter qu'il a un compte créé mais non activé, et affichera de nouveau cet écran
- A la saisie du code : appel du user-service pour vérifier le code hashé en base et activation du compte.
- Reste à valider si ce service s'occupe de demander au auth-service un nouveau token avec le nouveau rôle, si le mobile appelle directement par la suite le auth-service pour réauthentifier l'utilisateur automatiquement avec le token linkedin, ou bien si le mobile demande à l'utilisateur de se reconnecter pour accéder à l'application avec un compte actif

Mettre tout ça dans un std.md pour valider la séquence d'activation du compte.

**Comment by cegiraud** [comment]
Allez voir le std.MD et réagissez ! :)

Si validé il faudra : 
 - ajouter un role "IN_VALIDATION"
- ajouter un endpoint sur auth-service qui appelera le user-service pour l'enregistrement du mail
- ajouter un endpoint sur auth-service qui appelera le user-service pour validation du code

**Comment by cegiraud** [comment]
TODO

Modifier le schéma pour ajouter un endpoint côté user service afin de déterminer si l'utilisateur a déjà saisi son mail. 
Supprimer le passage par auth-service pour la réception du mail et le rôle "IN_VALIDATION"

**Comment by cegiraud** [comment]
mise à jour de la std effectuée.
Il reste le point suivant.

On part sur quelle solution après avoir validé le mail de l'utilisateur  : 
- la validation du mail renvoie un nouveau token avec le nouveau rôle
- le mobile appelle directement auth-service pour réauthentifier l'utilisateur automatiquement avec le token linkedin
- le mobile demande à l'utilisateur de se reconnecter pour accéder à l'application avec un compte actif

Je pencherais plutôt pour le 1 ou 2

@cbarillet tu as un avis/recommandation ?

**Comment by cegiraud** [comment]
solution retenue: la deux.
