### ISSUE TITLE
Génération de code de connexion et envoi de l'email

### ISSUE THREAD

**Issue by rjansem** [SopraSteriaGroup/initiatives_backend#8]
Génération du code de connexion
Envoi de l'email avec ce code de connexion
Génération de l'URL de validation du compte

**Comment by cegiraud** [comment]
Il s'agit de mettre une validation par deux biais c'est ça ? Un code pin et une URL et l'utilisateur choisi l'un ou l'autre ?

**Comment by rjansem** [comment]
Non, lors de la première connexion le user tape son email sopra, et le Ws l'insère dans la table des users, génère un code et envoie ce code par email dans une URL (ou pas)

Puis au clic cette URL / saisie du code qqpart, le compte est activé en base

**Comment by cegiraud** [comment]
D'accord donc on est bien en phase. 
Est-ce qu'on attribue un rôle à un user qui n'a pas encore validé son adresse?

**Comment by cegiraud** [comment]
generation + envoi de mail avec code.
L'utilisateur devra le renseigner via l'ihm (cf #9 )
utilisation de http://danfarrelly.nyc/MailDev/ pour mocker le serveur smtp
